// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://huxhlktqxdkafbjtbwyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eGhsa3RxeGRrYWZianRid3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjUyNDMsImV4cCI6MjA3Mzk0MTI0M30.JWJbsLcVxLnBzaaMFTTl0CNLg0olbtdLNSUhQGku_yI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Debug function to verify configuration
export const debugSupabaseConfig = () => {
  console.log('Supabase Configuration:');
  console.log('URL:', SUPABASE_URL);
  console.log('Key (first 20 chars):', SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...');
  console.log('Environment variables loaded:', {
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL ? 'loaded' : 'missing',
    VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? 'loaded' : 'missing'
  });
};